export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry'
] as const

export const DELHI_FAMOUS_PLACES = [
  'Dwarka',
  'Saket',
  'Vasant Kunj',
  'Rohini',
  'Janakpuri',
  'Connaught Place',
  'Karol Bagh',
  'Lajpat Nagar',
  'Greater Kailash',
  'Hauz Khas',
  'Nehru Place',
  'Rajouri Garden',
  'Pitampura',
  'Dwarka Mor',
  'Uttam Nagar',
  'Shalimar Bagh',
  'Patel Nagar',
  'Mayur Vihar',
  'Laxmi Nagar',
  'Okhla',
  'Chanakyapuri',
  'Defence Colony',
  'Green Park',
  'Safdarjung',
  'Paschim Vihar',
  'Vikaspuri',
  'Model Town',
  'Civil Lines',
  'Punjabi Bagh',
  'Vasant Vihar',
  'RK Puram',
  'Munirka',
  'Kalkaji',
  'Malviya Nagar',
  'Preet Vihar',
  'Shahdara',
  'Dilshad Garden',
  'Dwarka Sector 10',
  'Dwarka Sector 12',
  'Dwarka Sector 21',
  'Dwarka Sector 23',
  'Dwarka Sector 19',
  'Chhattarpur',
  'Safdarjung Enclave',
  'East of Kailash',
  'New Friends Colony'
] as const

export const NCR_CITIES = [
  'Gurugram',
  'Gurgaon',
  'Noida',
  'Greater Noida',
  'Faridabad',
  'Ghaziabad'
] as const

export const topCities = [
  "Mumbai",
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Chennai",
  "Delhi",
  "Gurgaon",
  "Noida",
  "Kolkata",
  "Ahmedabad",
  "Thane",
  "Navi Mumbai"
]

export const otherCities = [
  "Abohar", "Abu Dhabi", "Adilabad", "Agarmalwa", "Agartala", "Agra", "Ahmednagar", "Aizawl", "Ajman", "Ajmer", "Akola", "Alappuzha", "Alibag", "Aligarh", "Alipurduar", "Alirajpur", "Allahabad", "Almora", "Aluva", "Alwar", "Ambala", "Ambedkar Nagar", "Amethi", "Amravati", "Amreli", "Amritsar", "Amroha", "Anand", "Anantapur", "Anantnag", "Angul", "Anjaw", "Ankleshwar", "Anuppur", "Araria", "Aravalli", "Ariyalur", "Arrah", "Arwal", "Asansol", "Ashoknagar", "Auraiya", "Aurangabad", "Aurangabad, Bihar", "Ayodhya", "Azamgarh",
  "Baddi", "Badgam", "Bagalkot", "Bageshwar", "Baghpat", "Bahadurgarh", "Bahraich", "Baksa", "Balaghat", "Balangir", "Balasore", "Ballia", "Balod", "Balrampur", "Banaskantha", "Banda", "Bandipora", "Banka", "Bankura", "Banswara", "Barabanki", "Baramulla", "Baran", "Bardhaman", "Bareilly", "Bargarh", "Barmer", "Barnala", "Barpeta", "Barwani", "Bastar", "Basti", "Bathinda", "Bauda", "Beawar", "Beed", "Begusarai", "Belagavi", "Bellary", "Bemetara", "Berhampore", "Bettiah", "Betul", "Bhadohi", "Bhadrak", "Bhagalpur", "Bhandara", "Bharatpur", "Bharuch", "Bhatapara", "Bhavnagar", "Bhilai", "Bhilwara", "Bhimavaram", "Bhind", "Bhiwadi", "Bhiwani", "Bhojpur", "Bhopal", "Bhubaneswar", "Bhuj", "Bidar", "Bihar Sharif", "Bijapur", "Bijnor", "Bikaner", "Bilaspur", "Bilaspur, HP", "Bilimora", "Birbhum", "Bishnupur", "Bokaro", "Bolpur-Santiniketan", "Bongaigaon", "Botad", "Brajrajnagar", "Budaun", "Bulandshahr", "Buldhana", "Bundi", "Burhanpur", "Buxar",
  "Cachar", "Chamarajanagar", "Chamba", "Chamoli", "Champawat", "Champfh", "Chandauli", "Chandel", "Chandigarh", "Chandrapur", "Changlang", "Charkhi Dadri", "Chatra", "Chhapra", "Chhatarpur", "Chhindwara", "Chhota Udepur", "Chikkamagaluru", "Chiplun", "Chirang", "Chitradurga", "Chitrakoot", "Chittoor", "Chittorgarh", "Churachandpur", "Churu",
  "Coimbatore", "Cooch Behar", "Cuddalore", "Cuttack",
  "Dadra And Nagar Haveli", "Dahod", "Dakshin Dinajpur", "Dakshina Kannada", "Daltonganj", "Daman", "Damoh", "Dang", "Dantewada", "Dapoli", "Darbhanga", "Darjeeling", "Darrang", "Datia", "Dausa", "Davanagere", "Dehradun", "Dehri On Sone", "Deogarh", "Deoghar", "Deoria", "Dera Bassi", "Devbhoomi Dwarka", "Dewas", "Dhalai", "Dhamtari", "Dhanbad", "Dhar", "Dharamsala", "Dharmapuri", "Dharuhera", "Dhemaji", "Dhenkanal", "Dholera", "Dholka", "Dholpur", "Dhubri", "Dhule", "Dibang Valley", "Dibrugarh", "Dima Hasao", "Dimapur", "Dindigul", "Dindori", "Diu", "Doda", "Dubai", "Dumka", "Dungarpur", "Durg", "Durgapur",
  "East Garo Hills", "East Godavari", "East Jaintia Hills", "East Kameng", "East Khasi Hills", "East Siang", "East Sikkim", "East Singhbhum",
  "Eluru", "Ernakulam", "Erode", "Etah", "Etawah",
  "Faizabad", "Faridabad", "Faridkot", "Farrukhabad", "Fatehabad", "Fatehgarh Sahib", "Fatehpur", "Fazilka", "Firozabad", "Firozpur",
  "Gadag", "Gadchiroli", "Gajapati", "Gajraula", "Ganderbal", "Gandhinagar", "Gangtok", "Ganjam", "Garhwa", "Gariaband", "Gaya", "Ghaziabad", "Ghazipur", "Gift City", "Gir Somnath", "Giridih", "Goa", "Goalpara", "Godda", "Golaghat", "Gomati", "Gonda", "Gondal", "Gondia", "Gopalganj", "Gorakhpur", "Greater Noida", "Gudivada", "Gulbarga", "Gumla", "Guna", "Guntakal", "Guntur", "Gurdaspur", "Guwahati", "Gwalior",
  "Hailakandi", "Haldia", "Hamirpur", "Hanumangarh", "Hapur", "Harda", "Hardoi", "Haridwar", "Hassan", "Hathras", "Haveri", "Hazaribagh", "Himatnagar", "Hindupur", "Hingoli", "Hisar", "Hnahthial", "Hodal", "Hojai", "Hoshangabad", "Hoshiarpur", "Hospete", "Hosur", "Hubali-Dharwad",
  "Idukki", "Imphal", "Indore",
  "Jabalpur", "Jagadhri", "Jagatsinghpur", "Jagdalpur", "Jagraon", "Jagtial", "Jaipur", "Jaisalmer", "Jajpur", "Jalandhar", "Jalaun", "Jalgaon", "Jalna", "Jalore", "Jalpaiguri", "Jammu", "Jamnagar", "Jamshedpur", "Jamtara", "Jamui", "Jangaon", "Janjgir-Champa", "Jashpur", "Jaunpur", "Jayashankar Bhupalpally", "Jehanabad", "Jhabua", "Jhajjar", "Jhalawar", "Jhansi", "Jharsuguda", "Jhunjhunu", "Jind", "Jiribam", "Jodhpur", "Jogulamba Gadwal", "Jorhat", "Junagadh",
  "Kabirdham", "Kadapa", "Kaimur", "Kaithal", "Kakching", "Kakinada", "Kalahandi", "Kalimpong", "Kallakurichi", "Kalol", "Kamareddy", "Kamjong", "Kamrup", "Kanchipuram", "Kandhamal", "Kangpokpi", "Kangra", "Kanker", "Kannauj", "Kannur", "Kanpur", "Kanyakumari", "Kapurthala", "Karaikudi", "Karauli", "Karbi Anglong", "Kargil", "Karimganj", "Karimnagar", "Karnal", "Karur", "Karwar", "Kasaragod", "Kasganj", "Kashipur", "Kathua", "Katihar", "Katni", "Kaushambi", "Kendrapara", "Kendujhar", "Khagaria", "Khammam", "Khandwa", "Kharagpur", "Khargone", "Khawzawl", "Kheda", "Khordha District", "Khowai", "Khunti", "Kinnaur", "Kiphire", "Kishanganj", "Kishtwar", "Kochi", "Kodagu", "Kodaikanal", "Koderma", "Kohima", "Kokrajhar", "Kolasib", "Kolhapur", "Kollam", "Kondagaon", "Koppal", "Koraput", "Korba", "Koriya", "Kota", "Kothagudem", "Kottayam", "Kozhikode", "Krishna", "Krishnagiri", "Kulgam", "Kullu", "Kumuram Bheem Asifabad", "Kupwara", "Kurnool", "Kurukshetra", "Kushinagar", "Kutch",
  "Lahaul And Spiti", "Lakhimpur", "Lakhimpur Kheri", "Lakhisarai", "Lalitpur", "Latehar", "Latur", "Lawngtlai", "Leh", "Lohardaga", "Lohit", "Lonavala", "Longding", "Longleng", "Lower Dibang Valley", "Lower Siang", "Lower Subansiri", "Lucknow", "Ludhiana", "Lunglei",
  "Madanapalle", "Madhepura", "Markdown", "Madurai", "Mahabaleshwar", "Maharajganj", "Mahasamund", "Mahendragarh", "Mahisagar District", "Mahoba", "Mainpuri", "Malappuram", "Malda", "Malegaon", "Malkangiri", "Mamit", "Mancherial", "Mandi", "Mandla", "Mandsaur", "Mandya", "Mangalore", "Mansa", "Mathura", "Mau", "Mayiladuthurai", "Mayurbhanj", "Medak", "Meerut", "Mehsana", "Mewat", "Middle Andaman", "Mirzapur", "Modasa", "Moga", "Mohali", "Mokokchung", "Mon", "Moradabad", "Morbi", "Morena", "Morigaon", "Morinda", "Motihari", "Mulugu", "Mungeli", "Munger", "Murshidabad", "Mussoorie", "Muzaffarnagar", "Muzaffarpur", "Mysore",
  "Nabarangpur", "Nadia", "Nadiad", "Nagaon", "Nagapattinam", "Nagarkurnool", "Nagaur", "Nagercoil", "Nagpur", "Nainital", "Nalanda", "Nalbari", "Nalgonda", "Namakkal", "Namsai", "Nanded", "Nandurbar", "Nandyala", "Narasaraopet", "Narayanpet", "Narayanpur", "Narmada", "Narsinghpur", "Nashik", "Nathdwara", "Navsari", "Nawada", "Nawanshahr", "Nayagarh", "Neemrana", "Neemuch", "Nellore", "Nicobar", "Nilgiris", "Nirmal", "Nizamabad", "Noklak", "Noney", "North 24 Parganas District", "North Andaman", "North Garo Hills", "North Tripura", "Nuapada",
  "Ongole", "Ooty", "Osmanabad",
  "Pakur", "Palakkad", "Palamu", "Palanpur", "Pali", "Palwal", "Panchkula", "Panchmahal", "Panipat", "Panna", "Papum Pare", "Parbhani", "Pardi", "Pashchim Champaran", "Patan", "Pathanamthitta", "Pathankot", "Patiala", "Patna", "Pauri Garhwal", "Peddapalli", "Perambalur", "Peren", "Phagwara", "Phaltan", "Phek", "Pherzawl", "Pilibhit", "Pithoragarh", "Pollachi", "Poonch", "Porbandar", "Prakasam", "Pratapgarh", "Pratapgarh, UP", "Proddatur", "Puducherry", "Pudukkottai", "Pulwama", "Purba Medinipur", "Puri", "Purnea", "Purulia", "Purvi Champaran",
  "Raebareli", "Raichur", "Raigad", "Raigarh", "Raipur", "Raisen", "Rajahmundry", "Rajanna Sircilla", "Rajgarh", "Rajkot", "Rajnandgaon", "Rajouri", "Rajsamand", "Ramanathapuram", "Ramban", "Ramgarh", "Rampur", "Ranchi", "Ranikhet", "Ranipet", "Ras Al Khaimah", "Ratlam", "Ratnagiri", "Rayagada", "Reasi", "Rewa", "Rewari", "Ri Bhoi", "Rishikesh", "Rohtak", "Rohtas", "Roorkee", "Rourkela", "Rudraprayag", "Rudrapur", "Rupnagar", "Ruvak",
  "Sabarkantha", "Sagar", "Saharanpur", "Saharsa", "Sahibganj", "Salem", "Samastipur", "Samba", "Sambalpur", "Sambhal", "Sangli", "Sangrur", "Sant Kabir Nagar", "Saran", "Sasaram", "Satara", "Satna", "Sawaimadhopur", "Sehore", "Senapati", "Seoni", "Seraikela Kharsawan", "Serchhip", "Shahada", "Shahdol", "Shahjahanpur", "Shajapur", "Shamli", "Sheikhpura", "Sheohar", "Sheopur", "Shillong", "Shimla", "Shivamogga", "Shivpuri", "Shopian", "Shravasti", "Siaha", "Siang", "Siddharthnagar", "Siddipet", "Sidhi", "Sikar", "Silchar", "Siliguri", "Silvassa", "Simdega", "Sindhudurg", "Singapore", "Singrauli", "Sipahijala", "Sirmaur", "Sirohi", "Sirsa", "Sitamarhi", "Sitapur", "Sitarganj", "Sivaganga", "Sivasagar", "Siwan", "Sojat", "Solan", "Solapur", "Sonbhadra", "Sonipat", "Sonitpur", "South 24 Parganas", "South Andaman", "South Garo Hills", "South Tripura", "South West Khasi Hills", "Sri Ganganagar", "Sri Muktsar Sahib", "Srikakulam", "Srinagar", "Subarnapur", "Sukma", "Sultanpur", "Sundargarh", "Supaul", "Surajpur", "Surat", "Surendranagar", "Surguja", "Suryapet",
  "Tadepalligudem", "Tamenglong", "Tapi", "Tarn Taran Sahib", "Tawang", "Tehri", "Tenali", "Tengnoupal", "Tezpur", "Thanjavur", "Theni", "Thiruvananthapuram", "Thoothukudi", "Thoubal", "Thrissur", "Tikamgarh", "Tinsukia", "Tiruchengode", "Tiruchirappalli", "Tirunelveli", "Tirupathi", "Tirupathur", "Tiruppur", "Tiruvannamalai", "Tiruvarur", "Tonk", "Tuensang", "Tumkur",
  "Udaipur", "Udalguri", "Udham Singh Nagar", "Udhampur", "Udupi", "Ujjain", "Ukhrul", "Umargam", "Umaria", "Una", "Unakoti", "Unnao", "Upper Siang", "Upper Subansiri", "Uttar Dinajpur", "Uttara Kannada", "Uttarkashi District",
  "Vadodara", "Vaishali", "Valsad", "Vapi", "Varanasi", "Vellore", "Vidisha", "Vijayapura", "Vijayawada", "Vikarabad", "Viluppuram", "Virudhunagar", "Visakhapatnam", "Visnagar", "Vizianagaram", "Vrindavan",
  "Wanaparthy", "Warangal", "Wardha", "Washim", "Wayanad", "West Garo Hills", "West Godavari", "West Jaintia Hills", "West Kameng", "West Karbi Anglong", "West Khasi Hills", "West Medinipur", "West Siang", "West Singhbhum", "West Tripura", "Wokha",
  "Yadgir", "Yamuna Nagar", "Yavatmal",
  "Zirakpur", "Zunheboto"
]

