export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry'
] as const

export const DELHI_FAMOUS_PLACES = [
  'Dwarka',
  'Saket',
  'Vasant Kunj',
  'Rohini',
  'Janakpuri',
  'Connaught Place',
  'Karol Bagh',
  'Lajpat Nagar',
  'Greater Kailash',
  'Hauz Khas',
  'Nehru Place',
  'Rajouri Garden',
  'Pitampura',
  'Dwarka Mor',
  'Uttam Nagar',
  'Shalimar Bagh',
  'Patel Nagar',
  'Mayur Vihar',
  'Laxmi Nagar',
  'Okhla',
  'Chanakyapuri',
  'Defence Colony',
  'Green Park',
  'Safdarjung',
  'Paschim Vihar',
  'Vikaspuri',
  'Model Town',
  'Civil Lines',
  'Punjabi Bagh',
  'Vasant Vihar',
  'RK Puram',
  'Munirka',
  'Kalkaji',
  'Malviya Nagar',
  'Preet Vihar',
  'Shahdara',
  'Dilshad Garden',
  'Dwarka Sector 10',
  'Dwarka Sector 12',
  'Dwarka Sector 21',
  'Dwarka Sector 23',
  'Dwarka Sector 19',
  'Chhattarpur',
  'Safdarjung Enclave',
  'East of Kailash',
  'New Friends Colony'
] as const

export const NCR_CITIES = [
  'Gurugram',
  'Gurgaon',
  'Noida',
  'Greater Noida',
  'Faridabad',
  'Ghaziabad'
] as const

